[workspace]
authors = ["ManifoldFR", "Lucas-Haubert"]
channels = ["conda-forge"]
name = "nanoeigenpy"
description = "A support library for bindings between Eigen/C++ and Python, based on nanobind"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.3.0"
license = "BSD-3-Clause"
license-file = "LICENSE"

[tasks]
configure = { cmd = [
  "cmake",
  "-G",
  "Ninja",
  "-B",
  "build",
  "-S",
  ".",
  "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
  "-DCMAKE_BUILD_TYPE=$NANOEIGENPY_BUILD_TYPE",
  "-DBUILD_WITH_CHOLMOD_SUPPORT=$NANOEIGENPY_CHOLMOD_SUPPORT",
  "-DBUILD_WITH_ACCELERATE_SUPPORT=$NANOEIGENPY_ACCELERATE_SUPPORT",
] }
build = { cmd = "cmake --build build --target all", depends-on = ["configure"] }
clean = { cmd = "rm -rf build" }

[dependencies]
python = ">=3.9"
eigen = ">=3.3.1"
numpy = ">=1.22"
scipy = ">=1.10.0"

[feature.python-latest.dependencies]
python = "3.13.*"

[feature.python-oldest.dependencies]
python = "3.9.*"

[feature.cholmod]
dependencies = { suitesparse = ">=7" }
activation = { env = { NANOEIGENPY_CHOLMOD_SUPPORT = "ON" } }

# Accelerate only works on Apple ARM platforms
[feature.accelerate]
[feature.accelerate.target.osx-arm64]
activation = { env = { NANOEIGENPY_ACCELERATE_SUPPORT = "ON" } }

[feature.test.dependencies]
pytest = "*"

[activation]
scripts = ["development/scripts/pixi/activation.sh"]

[target.win-64.activation]
scripts = ["development/scripts/pixi/activation.bat"]

[build-dependencies]
nanobind = ">=2.5.0,<3"
cmake = ">=3.15"
cxx-compiler = ">=1.7"
ccache = ">=4.11.2"
ninja = ">=1.12.1"
pkg-config = ">=0.29.2"
git = ">=2.49.0"
doxygen = ">=1.13.2,<2"

[environments]
default =           {features = ["test", "python-latest"], solve-group = "py-latest"}
cholmod =           {features = ["test", "python-latest", "cholmod"], solve-group = "py-latest"}
accelerate =        {features = ["test", "python-latest", "accelerate"], solve-group = "py-latest"}
python-oldest =     {features = ["test", "python-oldest"], solve-group = "py-oldest"}
# NB: accelerate not supported with the current Eigen release, will be in next one
all =               {features = ["test", "python-latest", "cholmod"], solve-group = "py-latest"}
all-python-oldest = {features = ["test", "python-oldest", "cholmod"], solve-group = "py-oldest"}
