:: Set default build value only if not previously set
if not defined NANOEIGENPY_BUILD_TYPE (set NANOEIGENPY_BUILD_TYPE=Release)
if not defined NANOEIGENPY_CHOLMOD_SUPPORT (set NANOEIGENPY_CHOLMOD_SUPPORT=OFF)
if not defined NANOEIGENPY_ACCELERATE_SUPPORT (set NANOEIGENPY_ACCELERATE_SUPPORT=OFF)
